// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtDesS6CgCFwwtiHW_rN9PBoP4G55yg4o',
    appId: '1:832665252203:web:1c02ca6ed1ce0ea5ed1c2e',
    messagingSenderId: '832665252203',
    projectId: 'socialmediapp-99c84',
    authDomain: 'socialmediapp-99c84.firebaseapp.com',
    storageBucket: 'socialmediapp-99c84.firebasestorage.app',
    measurementId: 'G-MLE7T01EMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Om9TDcR-5pg7C9XnBWMjtmobyRqHBUU',
    appId: '1:832665252203:android:6983af14e0bfda2aed1c2e',
    messagingSenderId: '832665252203',
    projectId: 'socialmediapp-99c84',
    storageBucket: 'socialmediapp-99c84.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtDesS6CgCFwwtiHW_rN9PBoP4G55yg4o',
    appId: '1:832665252203:web:8aee9bd8e19b167ded1c2e',
    messagingSenderId: '832665252203',
    projectId: 'socialmediapp-99c84',
    authDomain: 'socialmediapp-99c84.firebaseapp.com',
    storageBucket: 'socialmediapp-99c84.firebasestorage.app',
    measurementId: 'G-FCRD97X4RL',
  );
}
